### ISSUE TITLE
Build fails with gcc/g++ 7.3 

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#107]
The code fails to build with gcc/g++ 7.3

> $ /media-driver/cmrtlib/agnostic/share/cm_printf_host.cpp:806:108: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
>              CM_PRINTF(m_streamOut,tkn, m_args[0], m_args[1], *((unsigned long long* )&(header->scalarLow32)));
>                                                                                                             ^
> $/media-driver/cmrtlib/agnostic/share/cm_printf_host.h:28:42: note: in definition of macro ‘CM_PRINTF’
>  #define CM_PRINTF(f_, ...) fprintf((f_), __VA_ARGS__)
>                                           ^~~~~~~~~~~
> cc1plus: all warnings being treated as errors
>

**Comment by HeFan2017** [comment]
Hi Haihao, I will check this issue.

**Comment by HeFan2017** [comment]
Hi Haihao. Commit 3e78136752641ff073e1c4ab0d3ec492c80b5d79 should fix this compiling issue shown in your log. Can you help confirm? Thanks a lot.

**Comment by oliver-sang** [comment]
@xhaihao
