### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by jbeich**
Depends on https://github.com/intel/libva/pull/363 and https://github.com/intel/gmmlib/pull/68

<details><summary>Build logs</summary>

http://beefy9.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/114amd64-default.log
http://beefy10.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/114i386-default.log
http://beefy6.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/122amd64-default.log
http://beefy5.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/122i386-default.log
http://beefy18.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/main-amd64-default.log
http://beefy17.nyi.freebsd.org/data/latest-per-pkg/libva-intel-media-driver/21.1.1/main-i386-default.log
https://sting.dragonflybsd.org/dports/logs/multimedia___libva-intel-media-driver.log
</details>

<details><summary>Tests output</summary>

```
[==========] Running 43 tests from 13 test cases.
[----------] Global test environment set-up.
[----------] 1 test from MediaCapsDdiTest
[ RUN      ] MediaCapsDdiTest.DecodeEncodeProfile
[       OK ] MediaCapsDdiTest.DecodeEncodeProfile (11 ms)
[----------] 1 test from MediaCapsDdiTest (11 ms total)

[----------] 2 tests from MediaDecodeDdiTest
[ RUN      ] MediaDecodeDdiTest.DecodeHEVCLong
[       OK ] MediaDecodeDdiTest.DecodeHEVCLong (6 ms)
[ RUN      ] MediaDecodeDdiTest.DecodeAVCLong
[       OK ] MediaDecodeDdiTest.DecodeAVCLong (10 ms)
[----------] 2 tests from MediaDecodeDdiTest (16 ms total)

[----------] 2 tests from MediaEncodeDdiTest
[ RUN      ] MediaEncodeDdiTest.EncodeHEVC_DualPipe
[       OK ] MediaEncodeDdiTest.EncodeHEVC_DualPipe (10 ms)
[ RUN      ] MediaEncodeDdiTest.EncodeAVC_DualPipe
[       OK ] MediaEncodeDdiTest.EncodeAVC_DualPipe (12 ms)
[----------] 2 tests from MediaEncodeDdiTest (22 ms total)

[----------] 5 tests from KernelTest
[ RUN      ] KernelTest.LoadDestroyProgram
[       OK ] KernelTest.LoadDestroyProgram (67 ms)
[ RUN      ] KernelTest.LoadWrongIsa
[       OK ] KernelTest.LoadWrongIsa (13 ms)
[ RUN      ] KernelTest.CreateKernel
[       OK ] KernelTest.CreateKernel (26 ms)
[ RUN      ] KernelTest.SetArgument
[       OK ] KernelTest.SetArgument (78 ms)
[ RUN      ] KernelTest.SetSamplerBTI
[       OK ] KernelTest.SetSamplerBTI (67 ms)
[----------] 5 tests from KernelTest (251 ms total)

[----------] 3 tests from BufferTest
[ RUN      ] BufferTest.MultipleSizes
[       OK ] BufferTest.MultipleSizes (79 ms)
[ RUN      ] BufferTest.ReadWrite
[       OK ] BufferTest.ReadWrite (13 ms)
[ RUN      ] BufferTest.Initialization
[       OK ] BufferTest.Initialization (14 ms)
[----------] 3 tests from BufferTest (106 ms total)

[----------] 2 tests from BufferUPTest
[ RUN      ] BufferUPTest.MultipleSizes
[       OK ] BufferUPTest.MultipleSizes (79 ms)
[ RUN      ] BufferUPTest.InvalidSystemMemory
[       OK ] BufferUPTest.InvalidSystemMemory (28 ms)
[----------] 2 tests from BufferUPTest (107 ms total)

[----------] 8 tests from DeviceTest
[ RUN      ] DeviceTest.Destroy
[       OK ] DeviceTest.Destroy (13 ms)
[ RUN      ] DeviceTest.NoScratchSpace
[       OK ] DeviceTest.NoScratchSpace (18 ms)
[ RUN      ] DeviceTest.QueryGpuPlatform
[       OK ] DeviceTest.QueryGpuPlatform (14 ms)
[ RUN      ] DeviceTest.QueryThreadCount
[       OK ] DeviceTest.QueryThreadCount (13 ms)
[ RUN      ] DeviceTest.QueryFrequency
[       OK ] DeviceTest.QueryFrequency (13 ms)
[ RUN      ] DeviceTest.QueryPlatformInformation
[       OK ] DeviceTest.QueryPlatformInformation (13 ms)
[ RUN      ] DeviceTest.SetThreadCount
[       OK ] DeviceTest.SetThreadCount (13 ms)
[ RUN      ] DeviceTest.GetInvalidCap
[       OK ] DeviceTest.GetInvalidCap (13 ms)
[----------] 8 tests from DeviceTest (111 ms total)

[----------] 2 tests from QueueTest
[ RUN      ] QueueTest.CreateTwice
[       OK ] QueueTest.CreateTwice (14 ms)
[ RUN      ] QueueTest.EnqueueWithoutTask
[       OK ] QueueTest.EnqueueWithoutTask (13 ms)
[----------] 2 tests from QueueTest (27 ms total)

[----------] 7 tests from Surface2DTest
[ RUN      ] Surface2DTest.MultipleSizes
[       OK ] Surface2DTest.MultipleSizes (172 ms)
[ RUN      ] Surface2DTest.PlanarFormats
[       OK ] Surface2DTest.PlanarFormats (80 ms)
[ RUN      ] Surface2DTest.DestroyNull
[       OK ] Surface2DTest.DestroyNull (14 ms)
[ RUN      ] Surface2DTest.ReadWrite
[       OK ] Surface2DTest.ReadWrite (29 ms)
[ RUN      ] Surface2DTest.ReadWriteWithStride
[       OK ] Surface2DTest.ReadWriteWithStride (14 ms)
[ RUN      ] Surface2DTest.Initialization
[       OK ] Surface2DTest.Initialization (13 ms)
[ RUN      ] Surface2DTest.GetInfo
[       OK ] Surface2DTest.GetInfo (27 ms)
[----------] 7 tests from Surface2DTest (349 ms total)

[----------] 3 tests from Surface2DUPTest
[ RUN      ] Surface2DUPTest.MultipleSizes
[       OK ] Surface2DUPTest.MultipleSizes (138 ms)
[ RUN      ] Surface2DUPTest.InvalidSystemMemory
[       OK ] Surface2DUPTest.InvalidSystemMemory (27 ms)
[ RUN      ] Surface2DUPTest.PlanarFormat
[       OK ] Surface2DUPTest.PlanarFormat (53 ms)
[----------] 3 tests from Surface2DUPTest (218 ms total)

[----------] 4 tests from Surface3DTest
[ RUN      ] Surface3DTest.MultipleSizes
[       OK ] Surface3DTest.MultipleSizes (135 ms)
[ RUN      ] Surface3DTest.Abgr16Format
[       OK ] Surface3DTest.Abgr16Format (27 ms)
[ RUN      ] Surface3DTest.ReadWrite
[       OK ] Surface3DTest.ReadWrite (13 ms)
[ RUN      ] Surface3DTest.Initialization
[       OK ] Surface3DTest.Initialization (14 ms)
[----------] 4 tests from Surface3DTest (189 ms total)

[----------] 1 test from TaskTest
[ RUN      ] TaskTest.CreateDestroy
[       OK ] TaskTest.CreateDestroy (14 ms)
[----------] 1 test from TaskTest (14 ms total)

[----------] 3 tests from ThreadSpaceTest
[ RUN      ] ThreadSpaceTest.MultipleSizes
[       OK ] ThreadSpaceTest.MultipleSizes (27 ms)
[ RUN      ] ThreadSpaceTest.DependencyPattern
[       OK ] ThreadSpaceTest.DependencyPattern (27 ms)
[ RUN      ] ThreadSpaceTest.MediaWalkingPattern
[       OK ] ThreadSpaceTest.MediaWalkingPattern (29 ms)
[----------] 3 tests from ThreadSpaceTest (84 ms total)

[----------] Global test environment tear-down
[==========] 43 tests from 13 test cases ran. (1505 ms total)
[  PASSED  ] 43 tests.
```
</details>

Note, to avoid regressing build in future consider [FreeBSD-friendly CI](https://wiki.freebsd.org/HostedCI).

### CODE REVIEW

**Comment by jbeich** [comment]
@iamleot, @iarebatman, can you test on NetBSD and OpenBSD? intel-vaapi-driver is deprecated in favor of media-driver. This PR fixes both DragonFly and FreeBSD but if it also fixes NetBSD and OpenBSD it'd increase upstream buy in. ;)

**Comment by iamleot** [comment]
Hello Jan,
Sure!  I'll hopefully be able to test it on NetBSD/amd64 later this UTC evening.  Unfortunately I only have 4th generation Intel CPUs so I think that I can only build test them.

Both https://github.com/intel/gmmlib/pull/68 and https://github.com/intel/media-driver/pull/819 NetBSD parts looks good to me after quick skimming them.

File: media_driver/linux/common/os/mos_utilities_specific.c [hunk 1]
```diff
@@ -2692,7 +2692,7 @@ uint32_t MOS_GetThreadId(
 
 uint32_t MOS_GetCurrentThreadId()
 {
-    return (uint32_t)pthread_self();
+    return (uintptr_t)pthread_self();
```
Comment (krytarowski) [inline media_driver/linux/common/os/mos_utilities_specific.c]: Here we should use `_lwp_self()` for NetBSD and `uint64_t` to be more portable.

File: media_driver/media_driver_next/linux/common/os/mos_utilities_specific_next.cpp [hunk 2]
```diff
@@ -1690,7 +1690,7 @@ uint32_t MosUtilities::MosGetThreadId(
 
 uint32_t MosUtilities::MosGetCurrentThreadId()
 {
-    return (uint32_t)pthread_self();
+    return (uintptr_t)pthread_self();
```
Comment (krytarowski) [inline media_driver/media_driver_next/linux/common/os/mos_utilities_specific_next.cpp]: Same here.

File: media_driver/linux/common/os/mos_utilities_specific.c (hunk 1 above)
Comment (jbeich) [reply media_driver/linux/common/os/mos_utilities_specific.c]: > Here we should use `_lwp_self()` for NetBSD

Wouldn't be consistent with Linux as `pthread_t` is not an integer representation of thread identifier. If the implementation doesn't make sense then it's a separate bug, out of scope for this PR.

<details><summary>pthread_self vs. gettid</summary>

```c
$ cc test.c -o test -lpthread
$ ./test
34366243136
45912

$ cat test.c
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>

#if defined(__BIONIC__)
#include <unistd.h>
#elif defined(__linux__)
#include <sys/syscall.h>
#elif defined(__DragonFly__) || defined(__FreeBSD__)
#include <pthread_np.h>
#elif defined(__NetBSD__)
#include <lwp.h>
#elif defined(__sun)
#include <thread.h>
#endif

#if !defined(__BIONIC__)
static pid_t gettid()
{
#if defined(__linux__)
  return syscall(__NR_gettid);
#elif defined(__DragonFly__) || defined(__FreeBSD__)
  return pthread_getthreadid_np();
#elif defined(__NetBSD__)
  return _lwp_self();
#elif defined(__OpenBSD__)
  return getthrid();
#elif defined(__sun)
  return thr_self();
#endif
}
#endif

int main()
{
  printf("%jd\n", (uintmax_t)pthread_self());
  printf("%jd\n", (uintmax_t)gettid());
}
```
</details>

> `uint64_t` to be more portable.

`uintptr_t` is already used in a number of places. media-driver only supports Intel architectures, so `uintptr_t` is either `uint32_t` or `uint64_t`.  On exotic platforms `uintptr_t` maybe smaller than `uint32_t` or larger than `uint64_t`. Even then using `uintptr_t` is likely more correct.

NetBSD i386 doesn't like `uint64_t` anyway:
```c
media_driver/linux/common/os/mos_utilities_specific.c: In function 'MOS_GetCurrentThreadId':
media_driver/linux/common/os/mos_utilities_specific.c:2695:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return (uint64_t)pthread_self();
            ^
```

Comment (krytarowski) [reply media_driver/linux/common/os/mos_utilities_specific.c]: I mean `uint32_t MOS_GetCurrentThreadId()` should be `uint64_t MOS_GetCurrentThreadId()`.. but if we really need a pointer to `pthread_t` here as ID, it is good to go for `uintptr_t` here.

Comment (jbeich) [reply media_driver/linux/common/os/mos_utilities_specific.c]: Out of scope. Submit a PR yourself. I'm not interested in fixing an API that's not even used for anything important.

Comment (krytarowski) [reply media_driver/linux/common/os/mos_utilities_specific.c]: OK. This patch is not making things worse than they already are.

**Comment by jbeich** [comment]
@iamleot, did you forget to test media-driver after gmmlib built fine? gmmlib is ~15x smaller than media-driver, so I expect more fun here.

(Just a reminder. I'll remove this comment shortly after.)

**Comment by iamleot** [comment]
Hello Jan,

Jan Beich writes:
> @iamleot, did you forget to test media-driver after gmmlib built fine? gmmlib is ~15x smaller than media-driver, so I expect more fun here.
>
> (Just a reminder. I'll remove this comment shortly after.)

No, I haven't and now that gmmlib seems ready I can finally test it.

I hope to test and share news this evening!
Thanks for the remainder and for working on that!

**Comment by jbeich** [comment]
@iamleot wrote:
> I hope to test and share news this evening!

Do you still plan to? See also https://github.com/intel/libva/pull/363

**Comment by iamleot** [comment]
Hello Jan,

Jan Beich writes:
> @iamleot wrote:
> > I hope to test and share news this evening!
>
> Do you still plan to? See also https://github.com/intel/libva/pull/363
>

Sorry for the delay and (upstream) please consider my test not blocking
(I was pretty busy in the last weeks).

I'll hopefully have more time this weekend but I couldn't promise
anything.

**Comment by jbeich** [comment]
Ugh, porting 6cafa0bf2aa114a397e77cdf9d9db0297c471c18 is harder than expected due to bundled libdrm. Intel didn't bother documenting exact revision the code was taken from and BSDs didn't bother upstreaming all of their patches.

**Comment by jbeich** [comment]
`cache` (including ccache) doesn't work due to TravisCI bug. If ~12 minutes is too long I can add a CirrusCI config.
```
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
$ Installing caching utilities
/home/travis/.rvm/scripts/set: /home/travis/.casher/bin/casher: /bin/bash: bad interpreter: No such file or directory
/home/travis/.rvm/scripts/set: line 19: /home/travis/.casher/bin/casher: No error: 0
```

**Comment by jbeich** [comment]
casher was fixed, so `cache` nowadays works but `ccache` in this repo doesn't for some reason:
> preprocessor error                   752

**Comment by tmm1** [comment]
Thanks for your work on this!

I'm trying to build on FreeBSD 12.1-STABLE and running into this:

```
intel-media-driver/build % make
Scanning dependencies of target igfxcmrt
[  0%] Building CXX object cmrtlib/linux/CMakeFiles/igfxcmrt.dir/hardware/cm_device_os.cpp.o
In file included from intel-media-driver/cmrtlib/linux/hardware/cm_device_os.cpp:24:
intel-media-driver/cmrtlib/linux/hardware/drm_device.h:947:6: error: #warning "Missing implementation of drmParseSubsystemType" [-Werror=cpp]
  947 |     #warning "Missing implementation of drmParseSubsystemType"
      |      ^~~~~~~
In file included from intel-media-driver/cmrtlib/linux/hardware/cm_device_os.cpp:24:
intel-media-driver/cmrtlib/linux/hardware/drm_device.h: In function 'bool drmNodeIsDRM(int, int)':
intel-media-driver/cmrtlib/linux/hardware/drm_device.h:252:19: error: 'DRM_MAJOR' was not declared in this scope
  252 |     return maj == DRM_MAJOR;
      |                   ^~~~~~~~~
cc1plus: all warnings being treated as errors
*** Error code 1
```

The first error I was able to fix with:

```diff
diff --git a/cmrtlib/linux/hardware/drm_device.h b/cmrtlib/linux/hardware/drm_device.h
index fa874521..8ef63fd7 100644
--- a/cmrtlib/linux/hardware/drm_device.h
+++ b/cmrtlib/linux/hardware/drm_device.h
@@ -941,7 +941,7 @@ static int drmParseSubsystemType(int maj, int min)
     }

     return -EINVAL;
-#elif defined(__OpenBSD__) || defined(__DragonFly__)
+#elif defined(__OpenBSD__) || defined(__DragonFly__) || defined(__FreeBSD__)
     return DRM_BUS_PCI;
 #else
     #warning "Missing implementation of drmParseSubsystemType"
```

**Comment by jbeich** [comment]
@tmm1, see https://github.com/intel/media-driver/pull/819#issuecomment-599480840

**Comment by jbeich** [comment]
Also, why are you build from this PR instead of using ports/packages?
https://www.freshports.org/multimedia/libva-intel-media-driver
https://www.freshports.org/multimedia/cmrtlib

**Comment by tmm1** [comment]
Thanks for the pointers!

File: cmrtlib/linux/hardware/drm_device.h [hunk 3]
```diff
@@ -39,16 +39,16 @@
...
 #define stat_t struct stat
 #include <sys/ioctl.h>
 #include <sys/time.h>
 #include <stdarg.h>
-#ifdef MAJOR_IN_MKDEV
+#ifdef __sun //#ifdef MAJOR_IN_MKDEV
 #include <sys/mkdev.h>
 #endif
-#ifdef MAJOR_IN_SYSMACROS
+#if defined(__GLIBC__) || defined(__linux__) //#ifdef MAJOR_IN_SYSMACROS
```
Comment (mattst88) [inline cmrtlib/linux/hardware/drm_device.h:51]: Why is this change correct?

File: cmrtlib/linux/hardware/drm_device.h [hunk 4]
```diff
@@ -39,16 +39,16 @@
...
 #include <time.h>
-#include <sys/sysmacros.h>   //<sys/types.h>
+#include <sys/types.h>
 #include <sys/stat.h>
 #define stat_t struct stat
 #include <sys/ioctl.h>
 #include <sys/time.h>
 #include <stdarg.h>
-#ifdef MAJOR_IN_MKDEV
+#ifdef __sun //#ifdef MAJOR_IN_MKDEV
```
Comment (mattst88) [inline cmrtlib/linux/hardware/drm_device.h:48]: Why is this change correct?

File: media_driver/linux/ult/libdrm_mock/xf86drm_mock.c [hunk 5]
```diff
@@ -47,16 +47,17 @@
...
 #include <time.h>
 #include <sys/types.h>
-#include <sys/sysmacros.h>
 #include <sys/stat.h>
 #define stat_t struct stat
 #include <sys/ioctl.h>
 #include <sys/time.h>
 #include <stdarg.h>
-#ifdef HAVE_SYS_MKDEV_H
+#ifdef __sun //#ifdef MAJOR_IN_MKDEV
```
Comment (mattst88) [inline media_driver/linux/ult/libdrm_mock/xf86drm_mock.c:55]: Same here.

File: media_driver/linux/ult/libdrm_mock/xf86drm_mock.c [hunk 6]
```diff
@@ -47,16 +47,17 @@
...
 # include <sys/mkdev.h> /* defines major(), minor(), and makedev() on Solaris */
 #endif
-#include <sys/sysmacros.h>
+#if defined(__GLIBC__) || defined(__linux__) //#ifdef MAJOR_IN_SYSMACROS
```
Comment (mattst88) [inline media_driver/linux/ult/libdrm_mock/xf86drm_mock.c:58]: Same here. Why not just `#ifdef MAJOR_IN_SYSMACROS`?

File: cmrtlib/linux/hardware/drm_device.h (hunk 3 above)
Comment (jbeich) [reply cmrtlib/linux/hardware/drm_device.h:51]: Because the bundled and patched libdrm is built via CMake and doesn't define `MAJOR_IN_SYSMACROS`. Instead always-true conditionals on Linux were expanded while the rest left as is. Are you suggesting to implement the macros via CMake?

Comment (jbeich) [reply cmrtlib/linux/hardware/drm_device.h]: Let's see if CMake checks pass CI.

Comment (jbeich) [reply cmrtlib/linux/hardware/drm_device.h]: *Sigh* CI is blocked by `1 workflow awaiting approval`. This hasn't been the case when TravisCI was still operational a year ago.

Comment (mattst88) [reply cmrtlib/linux/hardware/drm_device.h]: Oh, I see. I didn't realize this was a bundled libdrm file. Ugh.

Never mind then.

Comment (jbeich) [reply cmrtlib/linux/hardware/drm_device.h:51]: OK, reverted CMake checks. GNU libc disables extensions by default, so it breaks configure checks without `_GNU_SOURCE`. Debugging without a Linux machine/VM maybe hard.
```c++
-- Looking for major
-- Looking for major - not found
-- Looking for major
-- Looking for major - not found
[...]
In file included from cmrtlib/linux/hardware/cm_device_os.cpp:24:
cmrtlib/linux/../linux/hardware/drm_device.h:1041:11: error: use of undeclared identifier 'major'
    maj = major(sbuf.st_rdev);
          ^
cmrtlib/linux/../linux/hardware/drm_device.h:1042:11: error: use of undeclared identifier 'minor'
    min = minor(sbuf.st_rdev);
          ^
```
https://github.com/jbeich/media-driver/runs/4452912703

**Comment by dvrogozh** [comment]
As much as I wish to take this PR in, there is an issue that we have unpatched dependency (gmmlib). This means that the best we can do (w/o having permanently patched gmmlib) would be to setup ci based on PR against gmmlib - that's what is actually done in this PR. This has a problem however that we risk to have ci failures on gmmlib updates. Someone will need to fix PR against gmmlib. And ci fill be down during the time gmmlib PR is getting fixed. To be honest, this is not something I wish to setup and track.

I would suggest however to start picking up patches in this PR one by one reducing number of patches we have here. Some of them look to be ready to go, some might need further discussion.

**Comment by jbeich** [comment]
Obsoleted by #1785. Already [used downstream](https://github.com/freebsd/freebsd-ports/commit/bf2e205b04f5).

Personally, I gave up and use Vulkan Video (via anv from Mesa) or legacy intel-vaapi-driver (for hybrid VP9 decode) on my aging Skylake iGPU.
