### ISSUE TITLE
[Bug]: build of 23.1.5 with gcc 13 fails with array-bounds

### ISSUE THREAD

**Issue by heitbaum** [intel/media-driver#1641]
### Is it regression? Good in old configuration?

None

### What happened?

Build media-driver with gcc-13-20230402.
builds fine with gcc-12.2

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Build fails using gcc-13 20230402
``` 
In member function 'void encode::BufferQueue::SetResourceType(encode::ResourceType)',
    inlined from 'std::shared_ptr<encode::BufferQueue> encode::TrackedBuffer::GetBufferQueue(encode::BufferType)' at ../media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer.cpp:281:31:
../media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer_queue.h:90:65: error: array subscript 0 is outside array bounds of 'std::aligned_storage<184, 8>::type [0]' [-Werror=array-bounds=]
   90 |     void SetResourceType(ResourceType resType) { m_resourceType = resType; }
      |                                                  ~~~~~~~~~~~~~~~^~~~~~~~~
In member function 'std::shared_ptr<encode::BufferQueue> encode::TrackedBuffer::GetBufferQueue(encode::BufferType)':
cc1plus: note: source object is likely at address zero
cc1plus: all warnings being treated as errors
``` 

### Do you want to contribute a patch to fix the issue?

None

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-63403 for further analysis.
