### ISSUE TITLE
[Bug]: Build fails on IGFX_METEORLAKE 

### ISSUE THREAD

**Issue by zlice** [intel/media-driver#1577]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

Yes, it's good in old version

### Sys Info

- gcc 10.2.1
- cmake 3.25.0

### Issue

When trying to build current git or 22.6.4 the build fails with mentions of IGFX_METEORLAKE not being defined.

```
/builddir/intel-media-driver-22.6.4/media_driver/linux/common/ddi/media_libva_apo_decision.cpp: In static member function 'static bool MediaLibvaApoDecision::InitDdiApoState(int32_t, MediaUserSettingSharedPtr)':
/builddir/intel-media-driver-22.6.4/media_driver/linux/common/ddi/media_libva_apo_decision.cpp:46:26: error: 'IGFX_METEORLAKE' was not declared in this scope; did you mean 'IGFX_JASPERLAKE'?
   46 |     if (eProductFamily < IGFX_METEORLAKE)
      |                          ^~~~~~~~~~~~~~~
```

Commenting out mentions of meteorlake leads to another potential failure point.

```
/builddir/intel-media-driver-22.6.4/media_softlet/agnostic/Xe_M_plus/Xe_LPM_plus_base/hw/mhw_vebox_xe_lpm_plus_base_next_impl.h:2725:22: error: 'MEMORY_OBJECT_CONTROL_STATE' {aka 'union MEMORY_OBJECT_CONTROL_STATE_REC'} has no member named 'XE_LPG'; did you mean 'XE_HP'?
 2725 |                     .XE_LPG.Index;
      |                      ^~~~~~
      |                      XE_HP
```

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

None

**Comment by zlice** [comment]
Builds with gmmlib 22.3.2
