### ISSUE TITLE
[Bug]: Current master fails to build: missing VPHAL_PERFTAG definitions introduced after commit c7f82fffe

### ISSUE THREAD

**Issue by TedS04** [intel/media-driver#2016]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

None

### What happened?

Environment
Repository: intel/media-driver
Branch: master
Fresh clone
Ubuntu (latest)
CMake build using documented build procedure

Current master fails to compile because several VPHAL_PERFTAG-related identifiers are referenced but are never defined anywhere in the public repository.

The compiler reports errors such as: 
error: 'VPHAL_MCP_RENDER_COPY' was not declared in this scope
error: 'VPHAL_OCL_FC_FP_ROT' was not declared in this scope
error: 'VPHAL_OCL_FC_FP' was not declared in this scope

These originate from: 
media_softlet/agnostic/common/shared/mediacopy/media_copy_common.h
media_softlet/agnostic/common/vp/hal/features/vp_ocl_fc_filter.cpp

Confirmed latest master using git checkout master and git pull, repository is up to date.

Located where the missing identifiers are used:
VPHAL_MCP_RENDER_COPY: git grep VPHAL_MCP_RENDER_COPY 
Found in: media_softlet/agnostic/common/shared/mediacopy/media_copy_common.h

VPHAL_OCL_FC_FP: git grep VPHAL_OCL_FC_FP
Found in: media_softlet/agnostic/common/vp/hal/features/vp_ocl_fc_filter.cpp

Searched for the enum definitions
Searched for: 
git grep VPHAL_PERFTAG
git grep "enum.*VPHAL_PERFTAG"
git grep "typedef.*VPHAL_PERFTAG"
git grep VPHAL_OCL_FC_FP_ROT
git grep VPHAL_OCL_FC_ROT_1LAYER
git grep VPHAL_OCL_FC_PRI_1LAYER
git grep VPHAL_MCP_RENDER_COPY
git grep VPHAL_MCP_BLT_COPY

Result: The identifiers are used, but no enum or macro definitions exist anywhere in the repository.

Checked git history
Located commit introducing the feature: 
c7f82fffe
[Media Common] [VP] Add OCL FC Perf Tag and MCP PerfTag

History clearly shows the feature being added. However, searching the repository history for the definitions still does not locate any commit introducing the enum values.

Verified compile flags
Examined compile_commands.json.
Confirmed: correct include paths, no generated include, no -D VPHAL_PERFTAG, no forced include containing these definitions

Checked generated build tree
Searched build directory: grep -R VPHAL_PERFTAG build, grep -R VPHAL_OCL_FC_FP build, grep -R VPHAL_MCP_RENDER_COPY build

Only compiler error messages and binary object matches were found. No generated header defines these identifiers.

Verified source headers
Inspected: media_common/agnostic/common/vp/hal/vp_common_defs.h media_common/agnostic/common/vp/hal/vp_common.h
media_copy_common.h

No VPHAL_PERFTAG enum exists.

Compiler errors
The build fails with errors similar to:
media_copy_common.h

#define RENDER_COPY ((uint32_t)(VPHAL_MCP_RENDER_COPY))
                                ^~~~~~~~~~~~~~~~~~~~~
error: 'VPHAL_MCP_RENDER_COPY' was not declared in this scope

and

vp_ocl_fc_filter.cpp

perfTag = rotation
    ? VPHAL_PERFTAG(VPHAL_OCL_FC_FP_ROT)
    : VPHAL_PERFTAG(VPHAL_OCL_FC_FP);

error: 'VPHAL_OCL_FC_FP_ROT' was not declared
error: 'VPHAL_OCL_FC_FP' was not declared

Additional missing identifiers include:
VPHAL_OCL_FC_ROT_1LAYER
VPHAL_OCL_FC_PRI_1LAYER
VPHAL_OCL_FC_0LAYER

Either the missing VPHAL_PERFTAG enum/header should be present in the public repository, or these commits depend on another commit/header that was not merged into the public tree. At the moment, current master appears to reference identifiers that are never defined anywhere in the public source tree.

### What's the usage scenario when you are seeing the problem?

Transcode for media delivery

### Debug Information

libva-dev      2.22.0.2-87~u24.04
libva2         2.22.0.2-87~u24.04
libva-drm2     2.22.0.2-87~u24.04
libva-glx2     2.22.0.2-87~u24.04
libva-wayland2 2.22.0.2-87~u24.04
libva-x11-2    2.22.0.2-87~u24.04

LIBGMM_FOUND=1
LIBGMM_INCLUDEDIRS=/usr/include/igdgmm
LIBGMM_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu
LIBGMM_LIBRARIES=igdgmm

09:00.0 VGA compatible controller [0300]:
Intel Corporation Device [8086:e20b]

/dev/dri/
├── card0
└── renderD128

The issue occurs during compilation before the media-driver can be installed or executed, therefore: 
vainfo runtime log: Not applicable
LIBVA trace: Not applicable
GPU hang / dmesg: Not applicable

**Comment by XinfengZhang** [comment]
@peiyigu-intel

**Comment by XinfengZhang** [comment]
please update your gmmlib to be ensure this patch was involved: https://github.com/intel/gmmlib/commit/8ec33e1019f573b5df2aa5d1dabb66621065973a

**Comment by peiyigu-intel** [comment]
The issue is that only updated the driver repo but did not update the corresponding dependency gmmlib libraries.

Key Points:
The error saying "definition not found" is expected, because the definition was never in the MEDIA repo to begin with. However, since this is only adding to an existing enum (not creating a new one), the fact that it compiled before indicates the dependency library was simply not updated.

Timeline example:
Time Point A: VPHAL_VEBOX_P010 is used in the media repo, and is defined in gmmlib — this is a very old definition.
Time Point B: A new entry VPHAL_OCL_FC_0LAYER is added for use in the media repo, and the corresponding definition is added to gmmlib, with the open-source version also updated in sync.

Conclusion: please update gmmlib
https://github.com/intel/gmmlib/commit/8ec33e1019f573b5df2aa5d1dabb66621065973a

**Comment by MicroYY** [comment]
Hi @TedS04 Pls update gmmlib following media driver [release](https://github.com/intel/media-driver/releases) tag. Closing this issue as not a defect
