### ISSUE TITLE
[Bug]: build of 23.1.5 with gcc 13 fails with overloaded-virtual

### ISSUE THREAD

**Issue by heitbaum** [intel/media-driver#1639]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

None

### What happened?

Build media-driver with gcc-13-20230402.
builds fine with gcc-12.2

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Build fails using gcc-13 20230402
```
[155/1453] Building CXX object media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp.o
FAILED: 
…
media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp.o -MF media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp.o.d -o media_driver/CMakeFiles/iHD_drv_video_COMMON.dir/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp.o -c /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/media-driver-23.1.5/media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp
In file included from ../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_generic.h:31,
                 from ../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.h:30,
                 from ../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.cpp:26:
../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_generic.h: In instantiation of 'class MhwVdboxAvpInterfaceGeneric<mhw_vdbox_avp_g12_X>':
../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_g12_X.h:38:40:   required from here
../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_interface.h:779:24: error: 'virtual MOS_STATUS MhwVdboxAvpInterface::AddAvpBsdObjectCmd(PMOS_COMMAND_BUFFER, PMHW_BATCH_BUFFER, MhwVdboxAvpBsdParams*)' was hidden [-Werror=overloaded-virtual=]
  779 |     virtual MOS_STATUS AddAvpBsdObjectCmd(
      |                        ^~~~~~~~~~~~~~~~~~
../media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_generic.h:99:16: note:   by 'MOS_STATUS MhwVdboxAvpInterfaceGeneric<TAvpCmds>::AddAvpBsdObjectCmd(PMOS_COMMAND_BUFFER, MhwVdboxAvpBsdParams*) [with TAvpCmds = mhw_vdbox_avp_g12_X; MOS_STATUS = _MOS_STATUS; PMOS_COMMAND_BUFFER = _MOS_COMMAND_BUFFER*]'
   99 |     MOS_STATUS AddAvpBsdObjectCmd(
      |                ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

notes:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=20423
- gcc-13 includes -Woverloaded-virtual

### Do you want to contribute a patch to fix the issue?

None

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-63405 for further analysis.
