### ISSUE TITLE
[Bug]: Compiler reveals unnecessary NULL check resulting in build failure

### ISSUE THREAD

**Issue by cwilling** [intel/media-driver#1703]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

None

### What happened?

Build with GCC 13.1.0 produces error:
```
[ 83%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_SOFTLET_VP.dir/__/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline.cpp.o
/home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline.cpp: In member function ‘virtual MOS_STATUS vp::VpPipeline::PrepareVpPipelineScalabilityParams(PVP_PIPELINE_PARAMS)’:
/home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline.cpp:1107:22: error: the address of ‘VPHAL_RENDER_PARAMS::pSrc’ will never be NULL [-Werror=address]
 1107 |     if (params->pSrc == nullptr || params->pSrc[0] == nullptr)
      |         ~~~~~~~~~~~~~^~~~~~~~~~
In file included from /home/chris/src/media-driver/media_common/agnostic/common/vp/hal/vp_common.h:40,
                 from /home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline_common.h:31,
                 from /home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/features/vp_filter.h:32,
                 from /home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline.h:33,
                 from /home/chris/src/media-driver/media_softlet/agnostic/common/vp/hal/pipeline/vp_pipeline.cpp:28:
/home/chris/src/media-driver/media_common/agnostic/common/vp/hal/vp_common_defs.h:1001:20: note: ‘VPHAL_RENDER_PARAMS::pSrc’ declared here
```
Although revealed by recent gcc, if the error message is correct (address of ‘VPHAL_RENDER_PARAMS::pSrc’ will never be NULL) then the check for `params->pSrc == nullptr` can safely be removed for other compilers too - see #1702 

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Build fails.
Fixed with #1702

### Debug Information

libva-2.19.0-x86_64
libva-utils-2.19.0-x86_64
intel-gmmlib-22.3.9-x86_64
git master 25/7/2023
```
chris@d10:~/src/media-driver/build$ ls -l /dev/dri/
total 0
drwxr-xr-x  2 root root        80 Jul 25 09:20 by-path/
crw-rw----+ 1 root video 226,   0 Jul 25 09:20 card0
crw-rw-rw-  1 root video 226, 128 Jul 25 09:20 renderD128
```
```
chris@d10:~/src/media-driver/build$ lspci -nn |grep  -Ei 'VGA|DISPLAY'
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P Integrated Graphics Controller [8086:46a6] (rev 0c)
```
Other runtime logs not relevant

### Do you want to contribute a patch to fix the issue?

Yes, I'm glad to submit a patch to fix it

**Comment by cwilling** [comment]
I see this is now fixed by commit 4bc121084644caaed6b2183d8a4cc7a2dc4a3885
