### ISSUE TITLE
Build error with gcc8: clearing an object of non-trivial type ‘MHW_STATE_BASE_ADDR_PARAMS’

### ISSUE THREAD

**Issue by dbermond** [intel/media-driver#479]
I'm getting the following error when trying to build intel-media-driver git master with gcc8:

```
[ 13%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/codec/hal/codechal_decode_downsampling.cpp.o
/storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/codec/hal/codechal_decode_downsampling.cpp: In member function ‘MOS_STATUS FieldScalingInterface::DoFieldScaling(CODECHAL_DECODE_PROCESSING_PARAMS*, MOS_GPU_CONTEXT, bool, bool)’:
/storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/codec/hal/codechal_decode_downsampling.cpp:855:64: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘MHW_STATE_BASE_ADDR_PARAMS’ {aka ‘struct _MHW_STATE_BASE_ADDR_PARAMS’}; use assignment or value-initialization instead [-Werror=class-memaccess]
     memset(&stateBaseAddrParams, 0, sizeof(stateBaseAddrParams));
                                                                ^
In file included from /storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/codec/hal/codechal_hw.h:31,
                 from /storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/codec/hal/codechal_decoder.h:33,
                 from /storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/codec/hal/codechal_decode_downsampling.cpp:27:
/storage/linux/abs/intel-media-driver-git/src/media-driver/media_driver/agnostic/common/hw/mhw_render.h:123:16: note: ‘MHW_STATE_BASE_ADDR_PARAMS’ {aka ‘struct _MHW_STATE_BASE_ADDR_PARAMS’} declared here
 typedef struct _MHW_STATE_BASE_ADDR_PARAMS
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:739: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/codec/hal/codechal_decode_downsampling.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

- A git bisect shows that this is caused by commit https://github.com/intel/media-driver/commit/352456b6869fc67baf21312b9de043d501a7fcd2.

- It builds fine when using gcc 7.4.1, but fails to build with gcc 8.2.1.

- **System Information:**
  - **OS:** Arch Linux x86_64
  - **Compiler:** gcc 8.2.1
  - **cmake:** 3.13.1
  - **libpciaccess:** 0.14.1
  - **libva:** git master
  - **intel-gmmlib:** git master
  - **intel-media-driver:** git master
